export default {
  requiredField: 'Обов\'язкове поле',
  onlyCyrrilicSpaceDash: 'Тільки українська кирилиця, пробіли і тире',
  min2SymbolsWithoutSpaceDash: 'Мінімум 2 символи, крім пробілу та тире',
  min2Symbols: 'Мінімум 2 символи',
  ipnMustHave10Digits: 'ІПН повинен складатися з 10 цифр',
  wrongDateFormat: 'Невірний формат дати (дд.мм.рррр), рік від 1900 до 2099',
  wrongPhoneFormat: 'Невірний формат номера (+38(XXX) XXX XX XX)',
  wrongMailFormat: 'Невірний формат, приклад test@example.com',
  chooseOptionText: '--Вибрати--',
  min6ymbols: 'Мінімум 6 символів',
  onlySymbolsDigits: 'Допустимі лише букви та цифри',
  chooseDocType: 'Оберіть тип документу',
  docNumberRequired: 'Номер документу обовʼязковий',
  defaultUAPassportFormat: 'Формат укр. паспорта: 2 українські літери та 6 цифр',
  defaultUAOtherDocsFormat: 'Формат: 3 українські літери та від 5 до 9 цифр',
  idCardPassportFormat: 'Формат ID-карти: 9 цифр',
  unzrRequired: 'УНЗР обовʼязковий для ID-карти',
  unzrFormat: 'Формат УНЗР: 10 цифр, дефіс, 5 цифр (напр. 1234567890-12345)',
  noIPN: 'Немає РНОКПП (ІПН)',
  noMiddleName: 'Немає по батькові',
  idCardNotSelected: 'Запис № (УНЗР), потрібно вибрати ID-картку'
};
