import * as fieldNames from './fieldNames.js';
export default {
  [fieldNames.secondName]: 'Прізвище',
  [fieldNames.firstName]: 'Імя',
  [fieldNames.middleName]: 'По батькові',
  [fieldNames.dateOfBirth]: 'Дата народження',
  [fieldNames.gender]: 'Стать',
  [fieldNames.IPN]: 'РНОКПП(ІПН)',
  [fieldNames.countryOfBirth]: 'Країна народження',
  [fieldNames.placeOfBirth]: 'Місце народження',
  [fieldNames.preferedContactMethod]: 'Бажаний спосіб звязку із пацієнтом',
  [fieldNames.phone]: 'Контактний номер телефону',
  [fieldNames.email]: 'Адреса електронної почти',
  [fieldNames.secretQuestion]: 'Секретне слово (не менше 6 символів)',
  [fieldNames.documentType]: 'Тип документу',
  [fieldNames.docSeriaNumber]: 'Серія(за наявності), номер',
  [fieldNames.UNZR]: 'Запис № (УНЗР)',
  [fieldNames.docDateStart]: 'Коли видано',
  [fieldNames.docDateEnd]: 'Діє до',
  [fieldNames.docCreator]: 'Ким видано',
};
